In [16]:
import requests
import json 
import pandas as pd
from pandas.io.json import json_normalize

In [17]:
url = "https://api.github.com/repos/ta-data-lis/lab-mysql-first-queries/stats/participation"

response = requests.get(url)
response

In [20]:
result = response.json()
result

#norm_commits = json_normalize(result)
#norm_commits
df = pd.DataFrame(result)
df

    all  owner
0     0      0
1     0      0
2     0      0
3     0      0
4     0      0
5     0      0
6     0      0
7     0      0
8     0      0
9     0      0
10    0      0
11    0      0
12    0      0
13    0      0
14    0      0
15    0      0
16    0      0
17    0      0
18    0      0
19    0      0
20    0      0
21    0      0
22    0      0
23    0      0
24    0      0
25    0      0
26    0      0
27    0      0
28    0      0
29    0      0
30    0      0
31    0      0
32    0      0
33    0      0
34    0      0
35    0      0
36    0      0
37    0      0
38    0      0
39    0      0
40    4      0
41    0      0
42    0      0
43    0      0
44    0      0
45    0      0
46    0      0
47    0      0
48    0      0
49    0      0
50    0      0
51    0      0